package org.drools.examples

import org.drools.dotnet.examples


rule "New Ticket"
	salience 10
	when
		customer : Customer( )	
		ticket : Ticket( Customer == customer, Status == "New" )	
	then
		System.Console.Out.WriteLine( "New : " + ticket.toString() );		
end
 
rule "Silver Priority"
	duration 3000
	when
		customer : Customer( Subscription == "Silver" )	
		ticket : Ticket( Customer == customer, Status == "New" )	
	then
		ticket.Status =  "Escalate" ;
		modify( ticket );		
end

rule "Gold Priority"
	duration 1000
	when
		customer : Customer( Subscription == "Gold" )	
		ticket : Ticket( Customer == customer, Status == "New" )	
	then
		ticket.Status =  "Escalate" ;	
		modify( ticket );		
end

rule "Platinum Priority"
	when
		customer : Customer( Subscription == "Platinum" )	
		ticket : Ticket( Customer == customer, Status == "New" )	
	then;
		ticket.Status =  "Escalate" ;
		modify( ticket );
end

rule "Escalate"
	when
		customer : Customer( )	
		ticket : Ticket( Customer == customer, Status == "Escalate" )	
	then
		sendEscalationEmail( customer, ticket );
end

rule "Done"
	when
		customer : Customer( )	
		ticket : Ticket( Customer == customer, Status == "Done" )	
	then
		System.Console.Out.WriteLine( "Done : " + ticket.toString() );		
end

function void sendEscalationEmail( Customer customer, Ticket ticket ) {
	System.Console.Out.WriteLine( "Email : " + ticket.toString() );
}