


package org.drools.test
import org.drools.dotnet.examples
rule "GoodBye"
	no-loop true
	when
		m : Message( status == Message.GOODBYE, message : message )
	then
		System.Console.Write(message);		
		m.message = "Hey There";
end
rule "Hello World"
	when
		m : Message( status == Message.HELLO ,message : message )
	then		
		System.Console.Write(message);
		System.Console.Write("\n");
		m.message = "Goodbye cruel world";
		m.status =  Message.GOODBYE;
		modify( m );
end